import { Ionicons } from '@expo/vector-icons';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { TradeCard } from '../components/TradeCard';
import { SummaryCard } from '../components/SummaryCard';
import { SignalBadge } from '../components/SignalBadge';
import { mockTrades } from '../data/mockTrades';
import { AppScreenProps } from '../navigation/AppNavigator';
import { colors } from '../theme/colors';
import { formatCurrency } from '../utils/formatters';

type Props = AppScreenProps<'Home'>;

export function HomeScreen({ navigation }: Props) {
  const purchaseValue = mockTrades.filter((trade) => trade.type === 'Purchase').reduce((sum, trade) => sum + trade.value, 0);
  const saleValue = mockTrades.filter((trade) => trade.type === 'Sale').reduce((sum, trade) => sum + trade.value, 0);
  const signalCounts = mockTrades.reduce<Record<string, number>>((counts, trade) => ({ ...counts, [trade.signal]: (counts[trade.signal] ?? 0) + 1 }), {});
  const purchaseShare = Math.round((mockTrades.filter((trade) => trade.type === 'Purchase').length / mockTrades.length) * 100);
  const largestPurchase = mockTrades.filter((trade) => trade.type === 'Purchase').sort((first, second) => second.value - first.value)[0];
  const largestSale = mockTrades.filter((trade) => trade.type === 'Sale').sort((first, second) => second.value - first.value)[0];
  const strongestCeoSignal = mockTrades.filter((trade) => trade.role === 'CEO').sort((first, second) => second.signalStrength - first.signalStrength)[0];
  const topSignals = [
    { label: 'Largest purchase', trade: largestPurchase },
    { label: 'Largest sale', trade: largestSale },
    { label: 'Strongest CEO signal', trade: strongestCeoSignal },
  ];
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>INSIDER ACTIVITY</Text><Text style={styles.title}>Market signals</Text></View><View style={styles.live}><View style={styles.liveDot} /><Text style={styles.liveText}>DEMO MODE</Text></View></View>
    <View style={styles.demoBadge}><Ionicons name="sparkles-outline" size={14} color={colors.accent} /><Text style={styles.demoText}>Fictional sample data · static for this demo</Text></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Search sample trades" onPress={() => navigation.navigate('FindTrades')} style={styles.search}><Ionicons name="search-outline" size={19} color={colors.subtle} /><Text style={styles.searchPlaceholder}>Search ticker or company</Text><Ionicons name="arrow-forward" size={17} color={colors.accent} /></Pressable>
    <View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Market overview</Text><Text style={styles.sectionMeta}>{mockTrades.length} sample filings</Text></View>
    <View style={styles.summaryRow}><SummaryCard label="Total transactions" value={`${mockTrades.length}`} accent={colors.accent} /><SummaryCard label="Purchase value" value={formatCurrency(purchaseValue, true)} accent={colors.purchase} /><SummaryCard label="Sale value" value={formatCurrency(saleValue, true)} accent={colors.sale} /></View>
    <View style={styles.signalLine}><View><Text style={styles.signalLabel}>Activity mix</Text><Text style={styles.signalValue}>Purchase activity <Text style={styles.signalAccent}>↗ {purchaseShare}%</Text></Text></View><View style={styles.signalTrack}><View style={[styles.signalFill, { width: `${purchaseShare}%` }]} /></View></View>
    <View style={styles.categoryRow}>{([['Bullish', colors.purchase], ['Bearish', colors.sale], ['Watch', colors.watch]] as const).map(([label, accent]) => <View key={label} style={styles.category}><View style={[styles.categoryDot, { backgroundColor: accent }]} /><Text style={styles.categoryLabel}>{label}</Text><Text style={styles.categoryValue}>{signalCounts[label] ?? 0}</Text></View>)}</View>
    <View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Top signals</Text><Text style={styles.sectionMeta}>By sample data</Text></View>
    {topSignals.map(({ label, trade }) => <Pressable key={label} accessibilityRole="button" accessibilityLabel={`${label}: ${trade.company}, ${formatCurrency(trade.value, true)}. Open details`} onPress={() => navigation.navigate('Details', { tradeId: trade.id })} style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 13, marginBottom: 8 }}><View style={{ flex: 1 }}><Text style={{ color: colors.subtle, fontSize: 10, textTransform: 'uppercase', letterSpacing: 0.8 }}>{label}</Text><Text style={{ color: colors.text, fontSize: 13, fontWeight: '800', marginTop: 4 }}>{trade.ticker} · {trade.company}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 4 }}>{trade.insider} · {trade.role} · {formatCurrency(trade.value, true)}</Text></View><View style={{ alignItems: 'flex-end', gap: 8, marginLeft: 10 }}><SignalBadge signal={trade.signal} /><Ionicons name="chevron-forward" size={16} color={colors.subtle} /></View></Pressable>)}
    <View style={[styles.sectionHeading, { marginTop: 26 }]}><Text style={styles.sectionTitle}>Latest activity</Text><Pressable accessibilityRole="button" onPress={() => navigation.navigate('FindTrades')}><Text style={styles.viewAll}>View all</Text></Pressable></View>
    {mockTrades.slice(0, 4).map((trade) => <TradeCard key={trade.id} trade={trade} onPress={() => navigation.navigate('Details', { tradeId: trade.id })} />)}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.shell }, content: { padding: 20, paddingTop: 18, paddingBottom: 30 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: colors.accent, fontSize: 11, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.text, fontSize: 28, fontWeight: '800', marginTop: 5 }, live: { borderWidth: 1, borderColor: `${colors.purchase}55`, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', gap: 6 }, liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.purchase }, liveText: { color: colors.purchase, fontSize: 10, fontWeight: '800' }, demoBadge: { flexDirection: 'row', gap: 7, alignItems: 'center', backgroundColor: `${colors.accent}12`, borderRadius: 8, padding: 9, marginTop: 18 }, demoText: { color: colors.accent, fontSize: 11, fontWeight: '600' }, search: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 15, marginTop: 14, backgroundColor: colors.surface, borderRadius: 12, borderColor: colors.border, borderWidth: 1 }, searchPlaceholder: { flex: 1, color: colors.muted, fontSize: 14 }, sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 26, marginBottom: 12 }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '800' }, sectionMeta: { color: colors.subtle, fontSize: 11 }, summaryRow: { flexDirection: 'row', gap: 8 }, signalLine: { marginTop: 16, backgroundColor: colors.surface, borderRadius: 12, padding: 14, borderColor: colors.border, borderWidth: 1 }, signalLabel: { color: colors.subtle, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 }, signalValue: { color: colors.text, fontSize: 14, fontWeight: '700', marginTop: 5 }, signalAccent: { color: colors.purchase }, signalTrack: { height: 5, backgroundColor: colors.surfaceRaised, borderRadius: 3, marginTop: 13, overflow: 'hidden' }, signalFill: { width: '62%', height: '100%', backgroundColor: colors.purchase, borderRadius: 3 }, categoryRow: { flexDirection: 'row', gap: 8, marginTop: 10 }, category: { flex: 1, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 10, padding: 10 }, categoryDot: { width: 7, height: 7, borderRadius: 4 }, categoryLabel: { color: colors.subtle, fontSize: 10, marginTop: 8 }, categoryValue: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 2 }, viewAll: { color: colors.accent, fontSize: 12, fontWeight: '700' } });