import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MockActivityChart } from '../components/MockActivityChart';
import { SignalBadge } from '../components/SignalBadge';
import { mockTrades } from '../data/mockTrades';
import { RootStackParamList } from '../navigation/AppNavigator';
import { colors } from '../theme/colors';
import { formatCurrency, formatDate, formatNumber } from '../utils/formatters';

type Props = NativeStackScreenProps<RootStackParamList, 'Details'>;
export function TradeDetailsScreen({ route, navigation }: Props) {
  const trade = mockTrades.find((item) => item.id === route.params.tradeId) ?? mockTrades[0];
  const isPurchase = trade.type === 'Purchase';
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Pressable accessibilityLabel="Go back" onPress={() => navigation.goBack()} style={styles.back}><Ionicons name="arrow-back" size={21} color={colors.text} /><Text style={styles.backText}>All trades</Text></Pressable>
    <View style={styles.header}><View><Text style={styles.ticker}>{trade.ticker}</Text><Text style={styles.company}>{trade.company}</Text><Text style={styles.sector}>{trade.sector}</Text></View><SignalBadge signal={trade.signal} /></View>
    <View style={styles.badge}><Text style={styles.badgeText}>FICTIONAL DEMO DATA</Text></View>
    <View style={[styles.signalCard, { borderColor: `${isPurchase ? colors.purchase : colors.sale}65` }]}><View style={styles.signalCardTop}><Text style={styles.signalEyebrow}>SIGNAL SUMMARY</Text><Text style={styles.strength}>Signal score {trade.signalStrength}/100</Text></View><Text style={styles.signalTitle}>{trade.signal} activity</Text><Text style={styles.signalCopy}>{trade.insider}, {trade.role}, {isPurchase ? 'bought' : 'sold'} {formatNumber(trade.shares)} shares.</Text><View style={styles.strengthTrack}><View style={[styles.strengthFill, { width: `${trade.signalStrength}%`, backgroundColor: isPurchase ? colors.purchase : colors.sale }]} /></View></View>
    <Text style={styles.sectionTitle}>Trade details</Text><View style={styles.grid}>{[['Transaction', trade.type], ['Shares', formatNumber(trade.shares)], ['Price per share', formatCurrency(trade.pricePerShare)], ['Total value', formatCurrency(trade.value)], ['Filed on', formatDate(trade.filedAt)], ['Transaction code', trade.transactionCode]].map(([label, value]) => <View key={label} style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>)}</View>
    <View style={styles.chartHeader}><Text style={styles.sectionTitle}>7-day filing activity</Text><Text style={styles.chartMeta}>SAMPLE VOLUME</Text></View><MockActivityChart />
    <View style={styles.context}><Ionicons name="information-circle-outline" size={19} color={colors.accent} /><View style={styles.contextText}><Text style={styles.contextTitle}>How to read insider trades</Text><Text style={styles.contextCopy}>Executive transactions can add context to a company story, but one filing is never a standalone recommendation. Look for patterns, timing, and the size of the position.</Text></View></View>
    <Text style={styles.disclaimer}>LEGAL DISCLAIMER{`\n`}This fictional demo is for educational and interface demonstration purposes only. It is not investment advice, an offer, or a recommendation to buy or sell securities. All companies, people, tickers, and transactions are invented.</Text>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.shell }, content: { padding: 20, paddingTop: 16, paddingBottom: 36 }, back: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 26 }, backText: { color: colors.muted, fontSize: 13, fontWeight: '600' }, header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, ticker: { color: colors.text, fontSize: 32, fontWeight: '900', letterSpacing: 1 }, company: { color: colors.muted, fontSize: 15, marginTop: 4 }, sector: { color: colors.subtle, fontSize: 11, marginTop: 5 }, badge: { alignSelf: 'flex-start', marginTop: 18, backgroundColor: `${colors.accent}15`, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 5 }, badgeText: { color: colors.accent, fontSize: 9, letterSpacing: 1.1, fontWeight: '800' }, signalCard: { marginTop: 14, backgroundColor: colors.surface, borderWidth: 1, borderRadius: 14, padding: 16 }, signalCardTop: { flexDirection: 'row', justifyContent: 'space-between' }, signalEyebrow: { color: colors.subtle, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, strength: { color: colors.text, fontSize: 12, fontWeight: '800' }, signalTitle: { color: colors.text, fontSize: 20, fontWeight: '800', marginTop: 12 }, signalCopy: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 7 }, strengthTrack: { height: 5, backgroundColor: colors.surfaceRaised, borderRadius: 3, marginTop: 17 }, strengthFill: { height: '100%', borderRadius: 3 }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '800', marginTop: 26, marginBottom: 12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 1, backgroundColor: colors.border, borderRadius: 12, overflow: 'hidden' }, metric: { width: '49.8%', backgroundColor: colors.surface, padding: 13 }, metricLabel: { color: colors.subtle, fontSize: 10 }, metricValue: { color: colors.text, fontSize: 14, fontWeight: '700', marginTop: 6 }, chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, chartMeta: { color: colors.subtle, fontSize: 9, letterSpacing: 1 }, context: { flexDirection: 'row', gap: 10, backgroundColor: `${colors.accent}10`, borderRadius: 12, padding: 14, marginTop: 16 }, contextText: { flex: 1 }, contextTitle: { color: colors.accent, fontSize: 13, fontWeight: '800' }, contextCopy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, disclaimer: { color: colors.subtle, fontSize: 10, lineHeight: 15, marginTop: 22 } });